### ISSUE TITLE
ls: cannot access '/usr/lib/games/PCSX2 + /usr/local/bin/pcsx2-bootstrap: 125: exec: : Permission denied

### ISSUE THREAD

**Issue by Hadatko** [andrewmackrodt/dockerfiles#22]
Hi, i think i have it correctly now, but still getting these 
```bash
ls: cannot access '/usr/lib/games/PCSX2': No such file or directory
[WARN] BIOS is not set defaulting to SCPH7003.bin
/usr/local/bin/pcsx2-bootstrap: 125: exec: : Permission denied
```

```bash
version: "3.8"
services:
  pcsx2:
    image: andrewmackrodt/pcsx2-x11:latest
    container_name: pcsx2
    network_mode: local
    privileged: true
    environment:
      # - BIOS_ZIP=~/lastbld2.zip #web url
      # - BIOS_CHECKSUM=5d3b320e111fd3f8790bee3b64d160abc0a3abe4b5abf674a59d0324a1267398
      - PUID=1000
      - PGID=1000
      - DISPLAY=unix$DISPLAY
      - LANG=${LANG:-en_US.UTF-8}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /run/user/1000/pulse:/run/user/1000/pulse:ro
      - pcsx2_pulse:/home/ubuntu/.config/pulse:ro
      - /run/udev/data:/run/udev/data:ro
      - /etc/localtime:/etc/localtime:ro
      - pcsx2_PS2:/games:ro
      - pcsx2_data:/data
      - pcsx2_bios:/bios
      - pcsx2_plugins:/plugins
    devices:
      - /dev/input:/dev/input
      - /dev/snd:/dev/snd
      - /dev/dri:/dev/dri
    cap_add:
      - NET_ADMIN
    


volumes:
  pcsx2_PS2:
  pcsx2_data:
  pcsx2_bios:
  pcsx2_plugins:
  pcsx2_pulse:
```

**Comment by Hadatko** [comment]
I attached to the container:
```bash
root@doupe:/var/lib/docker/volumes/others_pcsx2_PS2/_data# docker run -it --entrypoint /bin/bash andrewmackrodt/pcsx2-x11
ubuntu@0cc4a85642f0:~$ ls
ubuntu@0cc4a85642f0:~$ ls /usr/local/bin/
PCSX2                 docker-entrypoint.sh  gosu                  pcsx2-bootstrap       tini                  
ubuntu@0cc4a85642f0:~$ ls /usr/local/bin/PCSX2  
/usr/local/bin/PCSX2
ubuntu@0cc4a85642f0:~$ which PCSX2
ubuntu@0cc4a85642f0:~$ 
ubuntu@0cc4a85642f0:~$ ls /usr/local/games/
ubuntu@0cc4a85642f0:~$ 
ubuntu@0cc4a85642f0:/usr/games$ ls -al
total 8
drwxr-xr-x 2 root root 4096 Apr 18  2022 .
drwxr-xr-x 1 root root 4096 Jan 22  2021 ..
```

**Comment by andrewmackrodt** [comment]
Hi @Hadatko thanks for reporting. I've not used these images in months and it looks to have broken after the interface changed to qt. I've pushed a fix to docker hub.

**Comment by Hadatko** [comment]
Hi @andrewmackrodt , thank you very much for quick update. Based on your tags on docker hub i thought you are actively work on that. https://hub.docker.com/r/andrewmackrodt/pcsx2-x11/tags

Anyway thank you. I still have some issues. Different one.
```bash
qt.qpa.xcb: could not connect to display unix
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, xcb.
/usr/bin/pcsx2-qt: line 2:   129 Aborted                 (core dumped) /opt/pcsx2-unstable/pcsx2-qt "$@"
```

Display issue is definitelly on my side and i need to fix it. Not sure if rest of errors are connected to that. I will try to debug in my evening hours.

**Comment by andrewmackrodt** [comment]
I have a Jenkins instance which performs nightly builds which is why the tags are up-to-date. What is your host platform and GPU? Are you running X11 or Wayland?

Based on the above error `qt.qpa.xcb: could not connect to display unix` it seems that `DISPLAY` is not set.

**Comment by Hadatko** [comment]
It looks like correct monitor fixed issues. Although you can see some wrong permissions settings at the beginning.
![image](https://github.com/andrewmackrodt/dockerfiles/assets/13130700/e897b22a-776c-4ce6-a73d-eef1e6c0f42b)

**Comment by Hadatko** [comment]
Made it working ;) Still some issues appering but generally it is working ;) Thank you for this option ;)
![image](https://github.com/andrewmackrodt/dockerfiles/assets/13130700/506f95f5-bffc-4ab9-bc9d-6e3b85fd9b65)
